<?php
$price_list = array(
  5 => '$1-$899',
  6 => '$900-$1299',
  7 => '$1300-$1699',
  8 => '$1700-$1999',
  9 => 'Over $2000'
);

$days_list = array(
  0 => 'Choose Duration',
  6 => 'Half Day',
  7 => '1 Day',
  8 => '2 Days',
  9 => '3 Days',
  10 => '4 Days',
  11 => '5 Days',
  12 => '6-7 Days',
  13 => '8-10 Days',
  14 => '11-15 Days',
  15 => 'Over 15 Days'
);

$city_list = array(
  1 => 'Beijing',
  2 => 'Shanghai',  
  3 => 'Xian',  
  4 => 'Guilin',
  5 => 'Tibet(Lhasa)',  
  6 => 'Huangshan',    
  7 => 'Chengdu',
  8 => 'Hangzhou',
  9 => 'Hong Kong',
  10 => 'Yangtze River',
  11 => 'Silk Road',
  12 => 'Suzhou',
  13 => 'Changsha',
  14 => 'Chengde',
  15 => 'Chongqing',
  16 => 'Dali',
  17 => 'Dalian',
  18 => 'Datong',
  19 => 'Dunhuang',
  20 => 'Guangzhou',
  21 => 'Guiyang',  
  22 => 'Harbin',
  23 => 'Hohhot',
  24 => 'Jiuzhaigou',
  25 => 'Kunming',
  26 => 'Kaili',
  //27 => 'Kashgar',
  28 => 'Lanzhou',
  29 => 'Luoyang',
  30 => 'Lijiang',
  31 => 'Longsheng',
  32 => 'Macau', 
  33 => 'Pingyao',
  34 => 'Qingdao',
  35 => 'Qinhuangdao',
  36 => 'Shangri-la',
  37 => 'Sanya',
  38 => 'Shenzhen',
  39 => 'Turpan',
  40 => 'Tianjin',
  41 => 'Urumqi',  
  42 => 'Wuhan',
  43 => 'Xining',
  44 => 'Xiamen',
  45 => 'Yangshuo',
  46 => 'Yichang',
  47 => 'Zhangjiajie'
);

$theme_list = array(
  1 => 'Top 10 China Tours',
  //2 => 'China Small Groups',
  19 => '2014 China Tours',
  3 => 'Cheap China Tours',
  4 => 'Student Tours',
  //4 => 'China Single City Tours',
  5 => 'Yangtze Cruise Tour',
  6 => 'China Train Travel',
  7 => 'Silk Road Adventure',
  8 => 'Minority Discovery',
  9 => 'China Tibet Tours',
  10 => 'China Architecture Tours',
  11 => 'China Adoption Travel',
  12 => 'China Food Tours',
  13 => 'China Religion Tours',
  14 => 'China World Heritage Tour',
  15 => 'China Skiing Tours',
  16 => 'China Honey Moon Tours',
  17 => 'China Golf Tour',
  18 => 'Luxury China Tours',
  20 => 'China Muslim Tour',
  21 => 'Classic China Tour',
  22 => 'China Family Tour',
);

$theme_num_list = array(
  1 => '10',
  3 => '24',
  4 => '15',
  5 => '20',
  6 => '11',
  7 => '9',
  8 => '21',
  9 => '18',
  10 => '6',
  11 => '28',
  12 => '21',
  13 => '10',
  14 => '23',
  15 => '5',
  16 => '7',
  17 => '5',
  18 => '25',
  20 => '47',
  21 => 12,
  22 => 10,
);

$china_highlights_list = array(
  1 => 'Great Wall of China',
  2 => 'Terra-cotta Warriors',
  3 => 'China Pandas',
  4 => 'Yellow Mountain',
  5 => 'Shaoling Kungfu',
  //6 => 'Hanging Temple',
  //7 => 'Longmen Cave',
  //8 => 'Jiuzhaigou',
  //9 => 'Zhangjiajie',
  10 => 'Zhouzhuang Water Town',
  //11 => 'The Bund',
  12 => 'Li River Cruise',
  //13 => 'Lijiang Old Town',
  14 => 'Potala Palace',

  15 => 'Forbidden City',
  16 => 'Temple of Heaven',
  17 => 'Hutong Rickshaw',
  18 => 'Big Wild Goose Pagoda',
  19 => 'Yuyuan Garden',
  20 => 'The Bund of Shanghai',
  21 => 'Stone Forest',
  22 => 'Yungang Grottoes',
  23 => 'Victoria Peak',
);

$china_highlights_num_list = array(
  1 => '115',
  2 => '55',
  3 => '14',
  4 => '9',
  5 => '10',
  6 => '7',
  7 => '6',
  8 => '2',
  9 => '2',
  10 => '18',
  11 => '31',
  12 => '13',
  13 => '9',
  14 => '16'
);


$season_list = array(
  1 => 'Spring',
  2 => 'Summer',
  3 => 'Autumn',
  4 => 'Winter'  
);

