<?php
return array(
  'price_list' => array(
    5 => '$1-$899',
    6 => '$900-$1299',
    7 => '$1300-$1699',
    8 => '$1700-$1999',
    9 => 'Over $2000'
  ),
  'days_list' => array(
    0 => 'Choose Duration',
    6 => 'Half Day',
    7 => '1 Day',
    8 => '2 Days',
    9 => '3 Days',
    10 => '4 Days',
    11 => '5 Days',
    12 => '6-7 Days',
    13 => '8-10 Days',
    14 => '11-15 Days',
    15 => 'Over 15 Days'
  ),

  'city_list' => array(
      1 => 'Beijing',
      2 => 'Shanghai',
      3 => 'Xian',
      4 => 'Guilin',
      5 => 'Tibet(Lhasa)',
      6 => 'Huangshan',
      7 => 'Chengdu',
      8 => 'Hangzhou',
      9 => 'Hong Kong',
      10 => 'Yangtze River',
      11 => 'Silk Road',
      12 => 'Suzhou',
      13 => 'Changsha',
      14 => 'Chengde',
      15 => 'Chongqing',
      16 => 'Dali',
      17 => 'Dalian',
      18 => 'Datong',
      19 => 'Dunhuang',
      20 => 'Guangzhou',
      21 => 'Guiyang',
      22 => 'Harbin',
      23 => 'Hohhot',
      24 => 'Jiuzhaigou',
      25 => 'Kunming',
      26 => 'Kaili',
      //27 => 'Kashgar',
      28 => 'Lanzhou',
      29 => 'Luoyang',
      30 => 'Lijiang',
      31 => 'Longsheng',
      32 => 'Macau',
      33 => 'Pingyao',
      34 => 'Qingdao',
      35 => 'Qinhuangdao',
      36 => 'Shangri-la',
      37 => 'Sanya',
      38 => 'Shenzhen',
      39 => 'Turpan',
      40 => 'Tianjin',
      41 => 'Urumqi',
      42 => 'Wuhan',
      43 => 'Xining',
      44 => 'Xiamen',
      45 => 'Yangshuo',
      46 => 'Yichang',
      47 => 'Zhangjiajie'
  ),

  'theme_list' => array(
      1 => 'Best China Tours',
      //2 => 'China Small Groups',
      21 => 'Classic China Tour',
      5 => 'Yangtze Cruise Tour',
      19 => '2014 China Tours',
      4 => 'Student Tours',
      22 => 'China Family Tour',
      9 => 'China Tibet Tours',
      6 => 'China Train Travel',
      7 => 'Silk Road Adventure',
      8 => 'Minority Discovery',
      //4 => 'China Single City Tours',
    
      20 => 'China Muslim Tour',
      18 => 'Luxury China Tours',
      3 => 'Cheap China Tours',
      10 => 'China Architecture Tours',
      12 => 'China Food Tours',
      13 => 'China Religion Tours',
      14 => 'China World Heritage Tour',
      15 => 'China Winter Tours',
      17 => 'China Golf Tour',
      11 => 'China Adoption Travel',
      16 => 'China Honey Moon Tours',
  ),

  'theme_num_list' => array(
        1 => '10',
        3 => '32',
        4 => '13',
        5 => '17',
        6 => '16',
        7 => '11',
        8 => '27',
        9 => '18',
        10 => '9',
        11 => '28',
        12 => '21',
        13 => '21',
        14 => '91',
        15 => '5',
        16 => '7',
        17 => '5',
        18 => '27',
        20 => '46',
        21 => '1',
        22 => '1',
   ),

  'china_highlights_list' => array(
    1 => 'Great Wall of China',
    2 => 'Terra-cotta Warriors',
    3 => 'China Pandas',
    4 => 'Yellow Mountain',
    5 => 'Shaoling Kungfu',
    //6 => 'Hanging Temple',
    //7 => 'Longmen Cave',
    //8 => 'Jiuzhaigou',
    //9 => 'Zhangjiajie',
    10 => 'Zhouzhuang Water Town',
    //11 => 'The Bund',
    12 => 'Li River Cruise',
    //13 => 'Lijiang Old Town',
    14 => 'Potala Palace',

    15 => 'Forbidden City',
    16 => 'Temple of Heaven',
    17 => 'Hutong Rickshaw',
    18 => 'Big Wild Goose Pagoda',
    19 => 'Yuyuan Garden',
    20 => 'The Bund of Shanghai',
    21 => 'Stone Forest',
    22 => 'Yungang Grottoes',
    23 => 'Victoria Peak',
  ),


  'china_highlights_num_list' => array(
      1 => '98',
      2 => '46',
      3 => '13',
      4 => '9',
      5 => '15',
      6 => '7',
      7 => '6',
      8 => '2',
      9 => '2',
      10 => '14',
      11 => '20',
      12 => '7',
      13 => '9',
      14 => '16'
    ),

    'season_list' => array(
      1 => 'Spring',
      2 => 'Summer',
      3 => 'Autumn',
      4 => 'Winter'
    ),
    
    'chinaGuideCity'=>array(
    	'picGuideCity'=>array('Beijing','Xian','Shanghai','Guilin','Lhasa',	'Hongkong'),
    	'otherGuideCity'=>array('Hangzhou','Luoyang','Harbin','Chengdu','Huangshan','Hohhot','Jiuzhaigou','Kunming','Guangzhou','Kashgar'),
    ),

  'currency' => array(
    'type' => array(    //货币类型
      1 => 'USD - United States Dollar',
      2 => 'CNY - Chinese Yuan',
      3 => 'EUR - Euro',
      4 => 'JPY-Japanese Yen', //日本日元
      5 => 'INR-Indian Rupee', //印度卢比
      6 => 'SUR-Russian Ruble', //俄罗斯卢布
      7 => 'DEM-Deutsche Mark', //德国马克
      8 => 'GBP-Pound Sterling', //德国马克
      9 => 'CAD-Canadian Dollar', //加拿大加元
      10 =>'AUD-Australian Dollar', //澳大利亚澳大利亚元
      11 => 'SAR-Saudi Arabian Riyal' //沙特阿拉伯亚尔
     ),  
    'exchange_rate' => array(  //货币类型对应汇率
       1 => 1,
       2 => '6.2197',
       3 => '0.7528',
       4 => '88.2950',
       5 => '54.6250',
       6 => '30.3355',
       7 => '0.2437',
       8 => '0.6225',
       9 => '0.9846',
      10 => '0.9467',
      11 => '3.7503'
     ), 
     'symbol' => array( //货币地应符号表示
       1 => '$',
       2 => '¥',
       3 => '€',
       4 => 'JPY',
       5 => 'INR',
       6 => 'SUR',
       7 => 'DEM',
       8 => '£',
       9 => 'CAD',
       10 => 'AUD',
       11 => 'CAD'
     )   
  ),  
  'attraction_city'=>array(
  	'A-G'=>array(
  		'Beijing'=>'hot',
  		'Chengdu'=>'hot',
  		'Chongqing'=>'',
  		'Changchun'=>'',
  		'Changsha'=>'',
  		'Chengde'=>'',
  		'Dali'=>'',
  		'Datong'=>'',
  		'Dunhuang'=>'hot',
  		'Fuzhou'=>'',
  		'Guangzhou'=>'',
  		'Guilin'=>'hot',
  		'Guiyang'=>'',
  	),
  	'H-N'=>array(
  		'Haikou'=>'',
  		'Hangzhou'=>'',
  		'Harbin'=>'hot',
  		'Huangshan'=>'hot',
  		'Hohhot'=>'',
  		'Hongkong'=>'hot',
  		'Jiuzhaigou'=>'',
  		'Jinan'=>'',
  		'Kunming'=>'',
  		'Kaifeng'=>'',
  		'Kashgar'=>'',
  		'Lhasa'=>'hot',
  		'Lijiang'=>'',
  		'Luoyang'=>'hot',
  		'Lanzhou'=>'',
  		'Macau'=>'',
  		'Nanchang'=>'',
  		'Nanjing'=>'',
  		'Nanning'=>'',
  	),
  	'P-Z'=>array(
  		'Pingyao'=>'hot',
  		'Qingdao'=>'',
  		'Sanya'=>'',
  		'Shanghai'=>'hot',
  		'Shijiazhuang'=>'',
  		'Shenyang'=>'',
  		'Shenzhen'=>'',
  		'Suzhou'=>'',
  		'Tibet'=>'hot',
  		'Taiyuan'=>'',
  		'Tianjin'=>'',
  		'Urumqi'=>'',
  		'Wuhan'=>'',
  		'Wuzhen'=>'hot',
  		'Xiamen'=>'',
  		'Xian'=>'',
  		'Xining'=>'',
  		'Yangshuo'=>'hot',
  		'Yinchuan'=>'',
  		'Zhangjiajie'=>'hot',
  		'Zhengzhou'=>'',
  	),
  ),
  'culture_city_tours'=>array('Beijing','Xi\'an','Harbin','Guilin','Luoyang','Dali','Lhasa','Kaifeng','Chengdu','Hangzhou'),
);
